package businesslogic_client.documentsbl;

import businesslogicservice_client.documentsblservice.ArrivalOrder4TranCenblservice;

public class ArrivalOrder4TranCen implements ArrivalOrder4TranCenblservice {

}
