package data_server.documentsdata.ArrivalOrder4TranCendata;

import dataservice_server.documentsdataservice.ArrivalOrder4TranCendataservice;

public class ArrivalOrder4TranCendata implements ArrivalOrder4TranCendataservice{

}
