package businesslogicservice_client_Stub.listblservice_Stub.informngmtlistblservice;

import businesslogicservice_client.listblservice.informngmtlistblservice.DriversInforlistblservice;

public class DriversInforlistblservice_Stub implements DriversInforlistblservice{

}
