package businesslogicservice_client_Stub.listblservice_Stub.informngmtlistblservice;

import businesslogicservice_client.listblservice.informngmtlistblservice.PersonnelAndAgencyInforlistblservice;

public class PersonnelAndAgencyInforlistblservice_Stub implements PersonnelAndAgencyInforlistblservice{

}
