package data_server.mngerandaccountantdata;

import dataservice_server.mngerandaccountantdataservice.InquireOperaLogdataservice;

public class InquireOperaLogdata implements InquireOperaLogdataservice{

}
