package businesslogic_client.listbl.documentslistbl;

import businesslogicservice_client.listblservice.documentslistblservice.ArrivalOrder4TranCenlistblservice;

public class ArrivalOrder4TranCenlistbl implements ArrivalOrder4TranCenlistblservice{

}
