package businesslogic_client.listbl.documentslistbl;

import businesslogicservice_client.listblservice.documentslistblservice.DeliveryOrderlistblservice;

public class DeliveryOrderlistbl implements DeliveryOrderlistblservice{

}
