package businesslogic_client.listbl.documentslistbl;

import businesslogicservice_client.listblservice.documentslistblservice.ReceivablesOrderlistblservice;

public class ReceivablesOrderlistbl implements ReceivablesOrderlistblservice{

}
