package businesslogic_client.listbl.documentslistbl;

import businesslogicservice_client.listblservice.documentslistblservice.TransferOrderlistblservice;

public class TransferOrderlistbl implements TransferOrderlistblservice{

}
