package businesslogic_client.listbl.informngmtlistbl;

import businesslogicservice_client.listblservice.informngmtlistblservice.DriversInforlistblservice;

public class DriversInforlistbl implements DriversInforlistblservice{

}
