package businesslogic_client.listbl.informngmtlistbl;

import businesslogicservice_client.listblservice.informngmtlistblservice.PersonnelAndAgencyInforlistblservice;

public class PersonnelAndAgencyInforlistbl implements PersonnelAndAgencyInforlistblservice{

}
