package businesslogicservice_client_Stub.listblservice_Stub;

import businesslogicservice_client.listblservice.OperaLoglistblservice;

public class OperaLoglistblservice_Stub implements OperaLoglistblservice{

}
