package businesslogicservice_client_Stub.listblservice_Stub;

import businesslogicservice_client.listblservice.OtherUsersListblservice;

public class OtherUsersListblservice_Stub implements OtherUsersListblservice{

}
