package businesslogicservice_client_Stub.listblservice_Stub;

import businesslogicservice_client.listblservice.Userlistblservice;

public class Userlistblservice_Stub implements Userlistblservice{

}
