package businesslogic_client.mngerandaccountantbl.approdocmbl;

import businesslogicservice_client.mngerandaccountantblservice.approdocmblservice.ApproDocmblservice;

public class ApproDocm implements ApproDocmblservice{

}
