package businesslogicservice_client_Stub.userblservice_Stub;

import businesslogicservice_client.userblservice.LoginAndOutblservice;

public class Loginblservice_Stub implements LoginAndOutblservice{

}
