package dataservice_client_Stub.stockdataservice_Stub;

import dataservice_client.stockdataservice.StorageListdataservice;

public class StorageListdataservice_Stub implements StorageListdataservice{

}
