package data_server.managerAndAccountantdata;

import dataservice_server.managerAndAccountantdataservice.InquireOperaLogdataservice;

public class InquireOperaLogdata implements InquireOperaLogdataservice{

}
