package dataservice_client_Stub.documentsdataservice_Stub;

import dataservice_client.documentsdataservice.LoadingListdataservice;

public class LoadingListdataservice_Stub implements LoadingListdataservice{

}
