package dataservice_client_Stub.documentsdataservice_Stub;

import dataservice_client.documentsdataservice.TransferOrderdataservice;

public class TransferOrderdataservice_Stub implements TransferOrderdataservice{

}
