package businesslogicservice_client_Stub.mngerandaccountantblservice_Stub;

import businesslogicservice_client.mngerandaccountantblservice.ApproDocmblservice;

public class ApproDocmblservice_Stub implements ApproDocmblservice{

}
