package businesslogicservice_client_Stub.mngerandaccountantblservice_Stub;

import businesslogicservice_client.mngerandaccountantblservice.OperaLogblservice;

public class OperaLogblservice_Stub implements OperaLogblservice{

}
