package businesslogicservice_client_Stub.mngerandaccountantblservice_Stub;

import businesslogicservice_client.mngerandaccountantblservice.StatisAnalyblservice;

public class StatisAnalyblservice_Stub implements StatisAnalyblservice{

}
