package businesslogicservice_client_Stub.documentsblservice_Stub;

import businesslogicservice_client.documentsblservice.ArrivalOrder4TranCenblservice;

public class ArrivalOrder4TranCenblservice_Stub implements ArrivalOrder4TranCenblservice{

}
