package businesslogicservice_client_Stub.documentsblservice_Stub;

import businesslogicservice_client.documentsblservice.DeliveryOrderblservice;

public class DeliveryOrderblservice_Stub implements DeliveryOrderblservice{

}
