package businesslogicservice_client_Stub.documentsblservice_Stub;

import businesslogicservice_client.documentsblservice.LoadingListblservice;

public class LoadingListblservice_Stub implements LoadingListblservice{

}
