package businesslogicservice_client_Stub.documentsblservice_Stub;

import businesslogicservice_client.documentsblservice.PaymentOrderblservice;

public class PaymentOrderblservice_Stub implements PaymentOrderblservice{

}
