package businesslogicservice_client_Stub.documentsblservice_Stub;

import businesslogicservice_client.documentsblservice.ReceivablesOrderblservice;

public class ReceivablesOrderblservice_Stub implements ReceivablesOrderblservice{

}
