package businesslogicservice_client_Stub.documentsblservice_Stub;

import businesslogicservice_client.documentsblservice.TransferOrderblservice;

public class TransferOrderblservice_Stub implements TransferOrderblservice{

}
