package dataservice_client_Stub.informngmtdataservice_Stub;

import dataservice_client.informngmtdataservice.DriversInfordataservice;

public class DriversInfordataservice_Stub implements DriversInfordataservice{

}
