package businesslogicservice_client_Stub.listblservice_Stub.stocklistblservice;

import businesslogicservice_client.listblservice.stocklistblservice.OutBoundOrderlistblservice;

public class OutBoundOrderlistblservice_Stub implements OutBoundOrderlistblservice{

}
