package businesslogic_client.listbl.stocklistbl;

import businesslogicservice_client.listblservice.stocklistblservice.OutBoundOrderlistblservice;

public class OutBoundOrderlistbl implements OutBoundOrderlistblservice{

}
