package businesslogicservice_client_Stub.informngmtblservice_Stub;

import businesslogicservice_client.informngmtblservice.BankAccountInforblservice;

public class BankAccountInforblservice_Stub implements BankAccountInforblservice{

}
