package businesslogicservice_client_Stub.informngmtblservice_Stub;

import businesslogicservice_client.informngmtblservice.DriversInforblservice;

public class DriversInforblservice_Stub implements DriversInforblservice{

}
