package businesslogicservice_client_Stub.informngmtblservice_Stub;

import businesslogicservice_client.informngmtblservice.PersonnelAndAgencyInforblservice;

public class PersonnelAndAgencyInforblservice_Stub implements PersonnelAndAgencyInforblservice{

}
