package businesslogicservice_client_Stub.informngmtblservice_Stub;

import businesslogicservice_client.informngmtblservice.VehiclesInforblservice;

public class VehiclesInforblservice_Stub implements VehiclesInforblservice{

}
