package businesslogicservice_client_Stub.listblservice_Stub.documentslistblservice;

import businesslogicservice_client.listblservice.documentslistblservice.ArrivalOrder4TranCenlistblservice;

public class ArrivalOrder4TranCenlistblservice_Stub implements ArrivalOrder4TranCenlistblservice{

}
